# Site settings
title: fairyland
subtitle: "Journal"
email: lunglungyu2004@gmail.com
description: "This guy has left nothing"
baseurl: ""
url: "http://lunglungyu.github.io"
#twitter_username: "lunglungyu"
github_username:  "lunglungyu"
#instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
style: :compressed
